header:
  version: 17

repos:
  bitbake:
    url: https://github.com/openembedded/bitbake
    layers:
      .: excluded

  openembedded-core:
    url: https://github.com/openembedded/openembedded-core
    layers:
      meta:

  meta-yocto:
    url: https://git.yoctoproject.org/meta-yocto
    layers:
      meta-yocto-bsp:
      meta-poky: excluded

  meta-openembedded:
    url: https://github.com/openembedded/meta-openembedded
    layers:
      meta-oe:
      meta-python:
      meta-networking:
      meta-gnome:
      meta-multimedia:

  meta-clang:
    url: https://github.com/kraj/meta-clang
    layers:
      .:

  meta-browser:
    url: https://github.com/OSSystems/meta-browser
    layers:
      meta-chromium:

  meta-house:
    layers:
      .:

env:
  BB_NUMBER_THREADS: null
  PARALLEL_MAKE: null

local_conf_header:
  disk: |
    DL_DIR = "/var/tmp/yocto_dl"
    BB_GIT_SHALLOW = "1"
    BB_GENERATE_SHALLOW_TARBALLS = "1"
    BB_GENERATE_MIRROR_TARBALLS = "1"
    BB_DISKMON_DIRS ??= " \
      STOPTASKS,${TMPDIR},1G,100K \
      STOPTASKS,${DL_DIR},1G,100K \
      STOPTASKS,${SSTATE_DIR},1G,100K \
      STOPTASKS,/tmp,100M,100K \
      HALT,${TMPDIR},100M,1K \
      HALT,${DL_DIR},100M,1K \
      HALT,${SSTATE_DIR},100M,1K \
      HALT,/tmp,10M,1K"
